name: 'PR Commenter'
description: 'Composite action to comment on a Pull Request'

inputs:
  message:
    description: 'Message to comment on the PR'
    required: true

runs:
  using: "composite"
  steps:
    - name: Comment on PR
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ inputs.message }}
