name: 'Node Setup & Linter'
description: 'Composite action to setup Node.js, install dependencies, and run lint'

inputs:
  node-version:
    description: 'Node.js version to setup'
    required: true
    default: '18'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    
    - name: Run linter
      run: npx eslint .
      shell: bash


    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run linter
      run: npm run lint
      shell: bash
