name: PR Auto Comment Workflow

on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Comment on PR
        uses: ./.github/custom-actions/pr-comment
        with:
          message: simple comment.